name: Generate and Deploy Market Schedule

on:
  # Run on push to main branch
  push:
    branches: [ main ]
  # Allow manual triggering
  workflow_dispatch:
  # Run once a day at 23.00 UTC
  schedule:
    - cron: '0 23 * * *'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Nix
        uses: cachix/install-nix-action@v31.3.0
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5.0.0

      - name: Generate schedule
        run: |
          nix develop --command python scheduler.py -o public/market_schedule.png
        shell: bash

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: \${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public

      - name: Override public/market_schedule.png
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"
          git add public/market_schedule.png
          git commit -m "Auto-update market schedule image" || echo "No changes"
          git push origin main
        shell: bash
